;invalid instructions, should not be highlighted
cwdqo
fbst
fcmovnbu
fiaddp/fisubp
cmovnpo/cmovpos
fucomipp
fidivp/fidivrp
ficomip/ficompp
fimulp
fisubp/fisubrp
paddub/padduw
cvtsi2pi/cvtps2ps/cvtsi2si/cvtpi2pi/cvtss2ss/cvtss2ps/cvtss2pi/cvtpi2ss
cvttsi2si/cvttps2ps/cvttpi2pi
cvttdq2ps
pmovsxww
vmovbe
vmovdq2q/vmovq2dq
vmovnti/vmovntq
vmovsx/vmovsxd
vmovzx
vmul
vpshufw
vfmsubadd132sd/vfmsubadd132ss/vfnmsubadd132pd
vfmaddsubsd/vfnmaddsubpd
vgatherds/vgatherdpq/vpgatherdqpd
xwait/iwait
outsq
padduw
popd/popq/popfdq
prefetcht3/prefetchta
psubuw
loopn
repn
sald/sard
broadcast/vvbroadcast
pmovsx/pmovzx
vbroadcast
vfnmaddsub213pd
xrdfsbase
vcvttusi2sd/vcvttusi2ss