vaddpd|vaddps|vaddsd|vaddss|valignd|valignq|vandpd|vandps|vandnpd|vandps

vblendmpd|vblendmps|vpblendmb|vpblendmw|vpblendmd|vpblendmq
vbroadcastss|vbroadcastsd|vpbroadcastb|vpbroadcastw|vpbroadcastd|vpbroadcastq
vbroadcastf128|vbroadcastf32x2|vbroadcastf32x4|vbroadcastf64x2|vbroadcastf32x8|vbroadcastf64x4
vbroadcasti128|vbroadcasti32x2|vbroadcasti32x4|vbroadcasti64x2|vbroadcasti32x8|vbroadcasti64x4
